---
title: "itp2"
format: html
---

## Preliminaries

We load the ~tidyverse~ packages in order to handle the databases:
```{r}
library(tidyverse)
```


## Data

Read the database files:
```{r}
load("./data/households.RData")
load("./data/individuals.RData")
load("./data/pov_transition.RData")
```

Add some variables to the ~pov_transition~ database:
```{r}
pov <- left_join(pov_transition, 
                 select(individuals, c(id_p, birth_year, absent)),
                 by = "id_p") 
```

Create a variable for the different cohorts:
```{r}
pov <- pov |> 
  mutate(cohort = factor(case_when(birth_year %in% 1960:1965 ~ "60_65",
                            birth_year %in% 1970:1975 ~ "70_75",
                            birth_year %in% 1980:1985 ~ "80_85"),
                         levels = c("60_65", "70_75", "80_85")))
```

Number of observations per cohort in each year:
```{r}
cohorts <- pov |>
  filter(!is.na(cohort)) 

cohorts |> 
  count(ecv_year, cohort) |> 
  pivot_wider(names_from = cohort, values_from = n)
```


